class Lis:
    def __init__ (self):
        self.act = elements0 = {
                "H": "H₂ + Cl₂ → 2HCl",
                "N": "N₂ + 3Cl₂ → 2NCl₃",
                "O": "O₂ + 2Cl₂ → 2Cl₂O",
                "F": "No direct reaction: F₂ + Cl₂ → No reaction",
                "Ne": "Ne + Cl₂ → No reaction",
                "Kr": "Kr + Cl₂ → KrCl₂ (theoretical, very unstable)",
                "Cl": "Cl₂ + Cl₂ → No reaction",
                "He": "He + Cl₂ → No reaction (Inert noble gas)",
                "Na": "2Na + Cl₂ → 2NaCl",
                "K": "2K + Cl₂ → 2KCl",
                "Ca": "Ca + Cl₂ → CaCl₂",
                "Fe": "2Fe + 3Cl₂ → 2FeCl₃",
                "Al": "2Al + 3Cl₂ → 2AlCl₃",
                "Cu": "Cu + Cl₂ → CuCl₂",
                "Zn": "Zn + Cl₂ → ZnCl₂",
                "Mg": "Mg + Cl₂ → MgCl₂",
                "P": "2P + 3Cl₂ → 2PCl₃ (or PCl₅ depending on conditions)",
                "S": "S + Cl₂ → SCl₂ (or S₂Cl₂ depending on conditions)",
                "C": "C + 2Cl₂ → CCl₄",
                "Si": "Si + 2Cl₂ → SiCl₄",
                "B": "2B + 3Cl₂ → 2BCl₃",
                "Sn": "Sn + Cl₂ → SnCl₂ (or SnCl₄ depending on conditions)",
                "Pb": "Pb + Cl₂ → PbCl₂ (or PbCl₄ under specific conditions)",
                "Ti": "Ti + 2Cl₂ → TiCl₄",
                "Ag": "2Ag + Cl₂ → 2AgCl",
                "Li": "2Li + Cl₂ → 2LiCl",
                "Rb": "2Rb + Cl₂ → 2RbCl",
                "Cs": "2Cs + Cl₂ → 2CsCl",
                "Fr": "2Fr + Cl₂ → 2FrCl",
                "Be": "Be + Cl₂ → BeCl₂",
                "Sr": "Sr + Cl₂ → SrCl₂",
                "Ba": "Ba + Cl₂ → BaCl₂",
                "Ra": "Ra + Cl₂ → RaCl₂",
                "Sc": "Sc + Cl₂ → ScCl₃",
                "V": "2V + 3Cl₂ → 2VCl₃",
                "Cr": "2Cr + 3Cl₂ → 2CrCl₃",
                "Mn": "Mn + Cl₂ → MnCl₂",
                "Ni": "Ni + Cl₂ → NiCl₂",
                "Zr": "Zr + 2Cl₂ → ZrCl₄",
                "Nb": "Nb + 2Cl₂ → NbCl₄",
                "Mo": "Mo + 2Cl₂ → MoCl₄",
                "Tc": "Tc + 2Cl₂ → TcCl₄",
                "Ru": "Ru + 2Cl₂ → RuCl₃",
                "Rh": "Rh + Cl₂ → RhCl₃",
                "Pd": "Pd + Cl₂ → PdCl₂",
                "Pt": "Pt + Cl₂ → PtCl₂",
                "Au": "2Au + 3Cl₂ → 2AuCl₃",
                "Hg": "Hg + Cl₂ → HgCl₂",
                "Lu": "Lu + 3Cl₂ → LuCl₃",
                "Hs": "Hs + Cl₂ → HsCl₂",
        "Co": "Co + Cl₂ → CoCl₂",
        "La": "La + 3Cl₂ → LaCl₃",
        "Ce": "Ce + 3Cl₂ → CeCl₃",
        "Pr": "Pr + 3Cl₂ → PrCl₃",
        "Nd": "Nd + 3Cl₂ → NdCl₃",
        "Pm": "Pm + 3Cl₂ → PmCl₃",
        "Sm": "Sm + 3Cl₂ → SmCl₃",
        "Eu": "Eu + 3Cl₂ → EuCl₃",
        "Gd": "Gd + 3Cl₂ → GdCl₃",
        "Tb": "Tb + 3Cl₂ → TbCl₃",
        "Dy": "Dy + 3Cl₂ → DyCl₃",
        "Ho": "Ho + 3Cl₂ → HoCl₃",
        "Er": "Er + 3Cl₂ → ErCl₃",
        "Tm": "Tm + 3Cl₂ → TmCl₃",
        "Yb": "Yb + 3Cl₂ → YbCl₃",
        "Ac": "Ac + 3Cl₂ → AcCl₃",
        "Th": "Th + 3Cl₂ → ThCl₄",
        "Pa": "Pa + 3Cl₂ → PaCl₄",
        "U": "U + 3Cl₂ → UCl₄",
        "Np": "Np + 3Cl₂ → NpCl₄",
        "Pu": "Pu + 3Cl₂ → PuCl₄",
        "Am": "Am + 3Cl₂ → AmCl₃",
        "Cm": "Cm + 3Cl₂ → CmCl₃",
        "Bk": "Bk + 3Cl₂ → BkCl₃",
        "Cf": "Cf + 3Cl₂ → CfCl₃",
        "Es": "Es + 3Cl₂ → EsCl₃",
        "Fm": "Fm + 3Cl₂ → FmCl₃",
        "Md": "Md + 3Cl₂ → MdCl₃",
        "No": "No + 3Cl₂ → NoCl₃",
        "Lr": "Lr + 3Cl₂ → LrCl₃",
        "Ga": "Ga + Cl₂ → GaCl₃",
        "In": "In + Cl₂ → InCl₃",
        "Tl": "Tl + Cl₂ → TlCl₃",
        "Bi": "Bi + Cl₂ → BiCl₃",
        "Po": "Po + Cl₂ → PoCl₂",

                }
        self.list1 = elements = [
     "H", "N", "O", "F", "Cl", "He", "Ne", "Kr", "Xe", "Rn",
    "Na", "K", "Ca", "Fe", "Al", "Cu", "Zn", "Mg", "P", "S",
    "C", "Si", "B", "Sn", "Pb", "Ti", "Ag", "Li", "Rb", "Cs",
    "Fr", "Be", "Sr", "Ba", "Ra", "Sc", "V", "Cr", "Mn", "Ni",
    "Zr", "Nb", "Mo", "Tc", "Ru", "Rh", "Pd", "Hf", "Ta", "W",
    "Re", "Os", "Ir", "Pt", "Au", "Hg", "Lu", "Hs", "Co", "La",
    "Ce", "Pr", "Nd", "Pm", "Sm", "Eu", "Gd", "Tb", "Dy", "Ho",
    "Er", "Tm", "Yb", "Ac", "Th", "Pa", "U", "Np", "Pu", "Am",
    "Cm", "Bk", "Cf", "Es", "Fm", "Md", "No", "Lr", "Ga", "In",
    "Tl", "Bi", "Po", "Ge", "Sb", "Te", "Se", "Br", "I", "At",
    "Y", "Cd", "As"
    ]
        self.list2 =  elements1 = [
            "Hydrogen", "Nitrogen", "Oxygen", "Fluorine", "Chlorine", "Helium", "Neon", "Krypton", "Xenon", "Radon",
"Sodium", "Potassium", "Calcium", "Iron", "Aluminum", "Copper", "Zinc", "Magnesium", "Phosphorus", "Sulfur",
"Carbon", "Silicon", "Boron", "Tin", "Lead", "Titanium", "Silver", "Lithium", "Rubidium", "Cesium",
"Francium", "Beryllium", "Strontium", "Barium", "Radium", "Scandium", "Vanadium", "Chromium", "Manganese", "Nickel",
"Zirconium", "Niobium", "Molybdenum", "Technetium", "Ruthenium", "Rhodium", "Palladium", "Hafnium", "Tantalum", "Tungsten",
"Rhenium", "Osmium", "Iridium", "Platinum", "Gold", "Mercury", "Lutetium", "Hassium", "Cobalt", "Lanthanum",
"Cerium", "Praseodymium", "Neodymium", "Promethium", "Samarium", "Europium", "Gadolinium", "Terbium", "Dysprosium", "Holmium","Erbium", "Thulium", "Ytterbium", "Actinium", "Thorium", "Protactinium", "Uranium", "Neptunium", "Plutonium", "Americium",
"Curium", "Berkelium", "Californium", "Einsteinium", "Fermium", "Mendelevium", "Nobelium", "Lawrencium", "Gallium", "Indium",
"Thallium", "Bismuth", "Polonium", "Germanium", "Antimony", "Tellurium", "Selenium", "Bromine", "Iodine", "Astatine",
"Yttrium", "Cadmium", "Arsenic"
        ]

    def ele(self):
        return self.list1
    def eleNames(self):
        return self.list2
    def eleAct(self):
        return self.act
